# Module - 1

# Data Pre-Processing

In [1]:
import pandas as p
import numpy as n

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
data = p.read_csv('WSN_Dataset.csv')

In [4]:
data.head()

id  Time  Is_CH  who_CH  Dist_To_CH  ADV_S  ADV_R  JOIN_S  JOIN_R  SCH_S  \
0   0    50      1  101000     0.00000      1      0       0      25      1   
1   1    50      0  101044    75.32345      0      4       1       0      0   
2   2    50      0  101010    46.95453      0      4       1       0      0   
3   3    50      0  101044    64.85231      0      4       1       0      0   
4   4    50      0  101010     4.83341      0      4       1       0      0   

   SCH_R  Rank  DATA_S  DATA_R  Data_Sent_To_BS  dist_CH_To_BS  send_code  \
0      0     0       0    1200               48      130.08535          0   
1      1     2      38       0                0        0.00000          4   
2      1    19      41       0                0        0.00000          3   
3      1    16      38       0                0        0.00000          4   
4      1    25      41       0                0        0.00000          3   

   Expaned_Energy Attack_type  
0         2.46940      Normal  
1         0.06957      Normal  
2         0.06898      Normal  
3         0.06673      Normal  
4         0.06534      Normal

In [5]:
data.shape

(50386, 19)

In [6]:
df = data.dropna()

In [7]:
df.shape

(50386, 19)

In [8]:
df.isnull().sum()

id                 0
Time               0
Is_CH              0
who_CH             0
Dist_To_CH         0
ADV_S              0
ADV_R              0
JOIN_S             0
JOIN_R             0
SCH_S              0
SCH_R              0
Rank               0
DATA_S             0
DATA_R             0
Data_Sent_To_BS    0
dist_CH_To_BS      0
send_code          0
Expaned_Energy     0
Attack_type        0
dtype: int64

In [9]:
df.columns

Index(['id', 'Time', 'Is_CH', 'who_CH', 'Dist_To_CH', 'ADV_S', 'ADV_R',
       'JOIN_S', 'JOIN_R', 'SCH_S', 'SCH_R', 'Rank', 'DATA_S', 'DATA_R',
       'Data_Sent_To_BS', 'dist_CH_To_BS', 'send_code', 'Expaned_Energy',
       'Attack_type'],
      dtype='object')

In [10]:
df.describe()

id          Time         Is_CH        who_CH    Dist_To_CH  \
count   50386.000000  50386.000000  50386.000000  5.038600e+04  50386.000000   
mean   144135.348906   1631.872663      0.692097  5.222792e+05      7.956177   
std    122135.673877   1136.619687      0.461631  5.710779e+05     20.769609   
min         0.000000     50.000000      0.000000  1.010000e+05      0.000000   
25%     12596.250000    553.000000      0.000000  1.120540e+05      0.000000   
50%    141644.500000   1503.000000      1.000000  4.011000e+05      0.000000   
75%    250151.750000   2703.000000      1.000000  7.010880e+05      0.000000   
max    374523.000000   3600.000000      1.000000  3.401100e+06    214.274620   

              ADV_S         ADV_R        JOIN_S        JOIN_R         SCH_S  \
count  50386.000000  50386.000000  50386.000000  50386.000000  50386.000000   
mean       1.800996     14.657504      0.212877      4.077482      2.050292   
std        5.328810     10.713167      0.409345     10.434079      7.262731   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      5.000000      0.000000      0.000000      0.000000   
50%        1.000000     11.000000      0.000000      0.000000      0.000000   
75%        1.000000     26.000000      0.000000      1.000000      1.000000   
max       97.000000     28.000000      1.000000    124.000000     99.000000   

              SCH_R          Rank        DATA_S        DATA_R  \
count  50386.000000  50386.000000  50386.000000  50386.000000   
mean       0.182809      4.075735      9.289922    155.757572   
std        0.386513     11.304608     24.922483    335.526372   
min        0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000     91.000000   
max        1.000000     99.000000    241.000000   1372.000000   

       Data_Sent_To_BS  dist_CH_To_BS     send_code  Expaned_Energy  
count     50386.000000   50386.000000  50386.000000    50386.000000  
mean         11.259794      47.503985      0.876533        0.459016  
std          34.375385      64.472742      2.361297        0.776257  
min           0.000000       0.000000      0.000000        0.000000  
25%           0.000000       0.000000      0.000000        0.007230  
50%           0.000000       0.000000      0.000000        0.049820  
75%          13.000000     112.103960      0.000000        0.508370  
max         241.000000     201.934940     15.000000        4.951570

In [11]:
df.Is_CH.unique()

array([1, 0], dtype=int64)

In [12]:
df.JOIN_R.unique()

array([ 25,   0,  30,   8,  33,  56,  42,  20,  48,  29,  32,  66,  15,
        12,   9,  18,  13,  14,  16,  27,   6,   5,  28,  50,  26,  19,
         4,  44,  46,   2,  11,  10,  23,  99,  17,   1,   3,   7,  24,
        21,  22,  35,  31,  63,  55,  51,  41,  61,  40,  90,  54,  47,
        82,  80,  38,  75,  39,  72,  62,  64,  36,  70,  52,  49,  59,
        60,  45,  95,  93,  98, 124,  97,  89,  43,  69,  53,  34,  96,
        37,  76,  65,  73,  79,  58,  71,  86,  78,  68,  67,  74,  57,
        88,  77,  81,  84,  94,  92,  83,  87,  85], dtype=int64)

In [13]:
df.send_code.unique()

array([ 0,  4,  3,  1,  2,  7,  5,  6,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int64)

In [14]:
p.crosstab(df.Attack_type,df.send_code)

send_code       0     1     2     3    4    5    6    7    8    9    10   11  \
Attack_type                                                                    
Blackhole    10049     0     0     0    0    0    0    0    0    0    0    0   
Flooding      3312     0     0     0    0    0    0    0    0    0    0    0   
Grayhole     14596     0     0     0    0    0    0    0    0    0    0    0   
Normal        5469  2621  1920  1573  926  672  464  530  286  167  208  252   
TDMA          6234   121   100    62   36   45   23   12    2    2    1    0   

send_code     12   13   14   15  
Attack_type                      
Blackhole      0    0    0    0  
Flooding       0    0    0    0  
Grayhole       0    0    0    0  
Normal       137  189  114  263  
TDMA           0    0    0    0

In [15]:
p.Categorical(df['Is_CH']).describe()

counts     freqs
categories                  
0            15514  0.307903
1            34872  0.692097

In [16]:
p.Categorical(df['send_code']).describe()

counts     freqs
categories                  
0            39660  0.787123
1             2742  0.054420
2             2020  0.040091
3             1635  0.032449
4              962  0.019093
5              717  0.014230
6              487  0.009665
7              542  0.010757
8              288  0.005716
9              169  0.003354
10             209  0.004148
11             252  0.005001
12             137  0.002719
13             189  0.003751
14             114  0.002263
15             263  0.005220

In [17]:
print("Time: ", sorted(df['Time'].unique()))

Time:  [50, 53, 100, 103, 150, 153, 200, 203, 250, 253, 300, 303, 350, 353, 400, 403, 450, 453, 500, 503, 550, 553, 600, 603, 650, 653, 700, 703, 750, 753, 800, 803, 850, 853, 900, 903, 908, 950, 953, 963, 1000, 1003, 1050, 1053, 1061, 1100, 1103, 1107, 1150, 1153, 1180, 1194, 1200, 1203, 1250, 1253, 1263, 1275, 1300, 1303, 1350, 1353, 1374, 1400, 1403, 1450, 1453, 1500, 1503, 1550, 1553, 1600, 1603, 1650, 1653, 1700, 1703, 1750, 1753, 1800, 1803, 1850, 1853, 1900, 1903, 1950, 1953, 2000, 2003, 2050, 2053, 2100, 2103, 2150, 2153, 2200, 2203, 2250, 2253, 2300, 2303, 2350, 2353, 2400, 2403, 2450, 2453, 2500, 2503, 2550, 2553, 2600, 2603, 2650, 2653, 2700, 2703, 2750, 2753, 2800, 2803, 2850, 2853, 2900, 2903, 2950, 2953, 3000, 3003, 3050, 3053, 3100, 3103, 3150, 3153, 3200, 3203, 3250, 3253, 3300, 3303, 3350, 3353, 3400, 3403, 3450, 3453, 3500, 3503, 3550, 3553, 3600]


In [18]:
print("ADV_R: ", sorted(df['ADV_R'].unique()))

ADV_R:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]


In [19]:
df['Attack_type'].value_counts()

Normal       15791
Grayhole     14596
Blackhole    10049
TDMA          6638
Flooding      3312
Name: Attack_type, dtype: int64

In [32]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
50381    False
50382    False
50383    False
50384    False
50385    False
Length: 50386, dtype: bool

In [33]:
df.duplicated().sum()

0

In [25]:
df.columns

Index(['id', 'Time', 'Is_CH', 'who_CH', 'Dist_To_CH', 'ADV_S', 'ADV_R',
       'JOIN_S', 'JOIN_R', 'SCH_S', 'SCH_R', 'Rank', 'DATA_S', 'DATA_R',
       'Data_Sent_To_BS', 'dist_CH_To_BS', 'send_code', 'Expaned_Energy',
       'Attack_type'],
      dtype='object')

In [26]:
print("Minimum value of Dist_To_CH is:", df.Dist_To_CH.min())
print("Maximum value of Dist_To_CH is:", df.Dist_To_CH.max())

Minimum value of Dist_To_CH is: 0.0
Maximum value of Dist_To_CH is: 214.27462000000003


In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50386 entries, 0 to 50385
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   id               50386 non-null  int64  
 1   Time             50386 non-null  int64  
 2   Is_CH            50386 non-null  int64  
 3   who_CH           50386 non-null  int64  
 4   Dist_To_CH       50386 non-null  float64
 5   ADV_S            50386 non-null  int64  
 6   ADV_R            50386 non-null  int64  
 7   JOIN_S           50386 non-null  int64  
 8   JOIN_R           50386 non-null  int64  
 9   SCH_S            50386 non-null  int64  
 10  SCH_R            50386 non-null  int64  
 11  Rank             50386 non-null  int64  
 12  DATA_S           50386 non-null  int64  
 13  DATA_R           50386 non-null  int64  
 14  Data_Sent_To_BS  50386 non-null  int64  
 15  dist_CH_To_BS    50386 non-null  float64
 16  send_code        50386 non-null  int64  
 17  Expaned_Ener

In [28]:
df['Attack_type'].unique()

array(['Normal', 'Flooding', 'TDMA', 'Grayhole', 'Blackhole'],
      dtype=object)

In [29]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['Attack_type']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(int)

In [30]:
df['Attack_type'].unique()

array([3, 1, 4, 2, 0])

In [31]:
df.tail()

id  Time  Is_CH  who_CH  Dist_To_CH  ADV_S  ADV_R  JOIN_S  JOIN_R  \
50381  373986   703      1  114021         0.0      1      6       0      26   
50382  374130   753      1  115065         0.0      1      4       0      55   
50383  374270   853      1  117005         0.0      1     10       0      14   
50384  374342   853      1  117078         0.0      1     10       0      11   
50385  374523   953      1  119061         0.0      1      6       0      31   

       SCH_S  SCH_R  Rank  DATA_S  DATA_R  Data_Sent_To_BS  dist_CH_To_BS  \
50381      1      0     0       0    1196                0            0.0   
50382      1      0     0       0    1320                0            0.0   
50383      1      0     0       0     745                0            0.0   
50384      1      0     0       0     921                0            0.0   
50385      1      0     0       0    1240                0            0.0   

       send_code  Expaned_Energy  Attack_type  
50381          0         0.00720            0  
50382          0         0.00722            0  
50383          0         0.00721            0  
50384          0         0.00726            0  
50385          0         0.00722            0